version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    environment:
      - DJANGO_SECRET_KEY=changeme
